# Generated by Django 6.1 on 2026-08-11 23:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransbankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buy_order', models.CharField(max_length=26, unique=True, verbose_name='Orden de Compra')),
                ('session_id', models.CharField(max_length=61, verbose_name='ID de Sesión')),
                ('tbk_token', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Token Webpay')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Transaccionado')),
                ('status', models.CharField(choices=[('INITIALIZED', 'Inicializada'), ('AUTHORIZED', 'Autorizada'), ('FAILED', 'Fallida / Rechazada')], db_index=True, default='INITIALIZED', max_length=15, verbose_name='Estado de Transacción')),
                ('authorization_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Autorización')),
                ('response_code', models.IntegerField(blank=True, null=True, verbose_name='Código Respuesta Banco')),
                ('payment_type_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de Pago')),
                ('shares_number', models.IntegerField(default=0, verbose_name='Número de Cuotas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='expenses.expensebill', verbose_name='Boleta Asociada')),
            ],
            options={
                'verbose_name': 'Transacción Webpay',
                'verbose_name_plural': 'Transacciones Webpay',
                'ordering': ['-created_at'],
            },
        ),
    ]
