# Generated by Django 6.1 on 2026-08-11 23:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Condominio')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT de la Comunidad')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Condominio',
                'verbose_name_plural': 'Condominios',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Número de Depto')),
                ('floor', models.IntegerField(default=1, verbose_name='Piso')),
                ('parking_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Estacionamiento')),
                ('storage_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Bodega')),
                ('share_percentage', models.DecimalField(decimal_places=6, help_text='Expresado en decimales. Ej: 0.025000 representa un 2.5% del total del edificio.', max_digits=7, validators=[django.core.validators.MinValueValidator(1e-06), django.core.validators.MaxValueValidator(1.0)], verbose_name='Alícuota / Porcentaje de Participación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='condo.condominium', verbose_name='Condominio')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to=settings.AUTH_USER_MODEL, verbose_name='Residente Asignado')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['number'],
                'unique_together': {('condominium', 'number')},
            },
        ),
    ]
