# Generated by Django 6.1 on 2026-08-11 23:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Gasto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción / Detalle')),
                ('period', models.DateField(help_text='Primer día del mes del cobro (ej: 2026-08-01)', verbose_name='Periodo')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto Total a Prorratear')),
                ('is_closed', models.BooleanField(default=False, verbose_name='¿Cerrado / Liquidado?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_expenses', to='condo.condominium', verbose_name='Condominio')),
            ],
            options={
                'verbose_name': 'Gasto Común Global',
                'verbose_name_plural': 'Gastos Comunes Globales',
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Calculado por Alícuota')),
                ('due_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('OVERDUE', 'Moroso')], db_index=True, default='PENDING', max_length=10, verbose_name='Estado de Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('common_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='expenses.commonexpense', verbose_name='Gasto Común Asociado')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='condo.department', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Boleta de Gasto Común',
                'verbose_name_plural': 'Boletas de Gastos Comunes',
                'ordering': ['-due_date'],
                'unique_together': {('department', 'common_expense')},
            },
        ),
    ]
