# Generated by Django 6.1 on 2026-08-12 00:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Espacio')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción / Reglamento')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Aforo Máximo (Personas)')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tarifa por Reserva ($)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Disponible')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios_comunes', to='condo.condominium', verbose_name='Condominio')),
            ],
            options={
                'verbose_name': 'Espacio Común',
                'verbose_name_plural': 'Espacios Comunes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Fecha/Hora Inicio')),
                ('end_time', models.DateTimeField(verbose_name='Fecha/Hora Término')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada')], db_index=True, default='CONFIRMED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('common_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='espacioscomunes.commonarea', verbose_name='Espacio Común')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='condo.department', verbose_name='Departamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Solicitante')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='reservation_end_time_after_start_time')],
            },
        ),
    ]
